### ISSUE TITLE
[BUG] Unknown color name "transparent"

### ISSUE THREAD

**Issue by guilhermecugler** [Akascape/CTkThemeMaker#4]
After import the theme.json generated by CTkThemeMaker
```
customtkinter.set_default_color_theme("theme.json")
```
I receive the output:

```
_tkinter.TclError: unknown color name "transparent"
```
Full traceback:

```
Traceback (most recent call last):
  File "project\main.py", line 158, in <module>
    appearance_mode_menu = ctk.CTkOptionMenu(app, values=["Sistema", "Escuro", "Claro"],
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "project\.venv\Lib\site-packages\customtkinter\windows\widgets\ctk_optionmenu.py", line 123, in __init__
    self._draw()  # initial draw
    ^^^^^^^^^^^^
  File "project\.venv\Lib\site-packages\customtkinter\windows\widgets\ctk_optionmenu.py", line 205, in _draw
    self._canvas.itemconfig("inner_parts_right",
  File "project\.venv\Lib\site-packages\customtkinter\windows\widgets\core_rendering\ctk_canvas.py", line 115, in itemconfig
    super().itemconfigure(configure_id, *args, **kwargs_except_outline)
  File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 2977, in itemconfigure
    return self._configure(('itemconfigure', tagOrId), cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\tkinter\__init__.py", line 1711, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown color name "transparent"
PS project> 
```

**Comment by Akascape** [comment]
@guilhermecugler Make sure that the colors in option menu are not set to transparent in the theme. If you reset any parameter, then it is set to "transparent" which is not a valid color for some ctk widgets.

**Comment by guilhermecugler** [comment]
> @guilhermecugler Make sure that the colors in option menu are not set to transparent in the theme. If you reset any parameter, then it is set to "transparent" which is not a valid color for some ctk widgets.

Ok, thanks!
I do not changed the default settings(so its transparent as default), only button colors, but I will change the options menu to fix it.
